language: python
python:
    - "3.8"
services: 
    - docker
install:
    - docker pull mkrum/stonefish
    - docker build --cache-from mkrum/stonefish . -t stonefish
script:
    - docker run --rm stonefish pytest -s
