apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stonefish-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Reduced size due to quota limitations
