
input_rep: !BoardRep
output_rep: !MoveRep

model: !BaseModel()
    emb_dim: 32
    num_encoder_layers: 1
    num_decoder_layers: 1

opt: !Adam()
    lr: !!float 1e-4

train_dl: !DataLoader()
    dataset: !CEChessData()
        path: /nfs/stonefish/data/train_mondo_5.csv 
    batch_size: 256
    shuffle: True
    drop_last: True

test_dl: !DataLoader()
    dataset: !CEChessData()
        path: /nfs/stonefish/data/test_mondo_5.csv 
    batch_size: 512
    shuffle: True
