

pretrain_context: !PreTrainContext()
    train_fn: !seq_train_step
    eval_fn: !seq_eval_model

    train_dl: !DataLoader()
        dataset: !ChessData()
            path: /nfs/stonefish/data/train_mondo_5.csv
            input_rep: !CBoardRep
            output_rep: !MoveRep
        batch_size: 512
        shuffle: True
        drop_last: True

    test_dl: !DataLoader()
        dataset: !ChessData()
            path: /nfs/stonefish/data/test_mondo_5.csv
            input_rep: !CBoardRep
            output_rep: !MoveRep
        batch_size: 512
        shuffle: True

model: !BaseModel()
    input_rep: !CBoardRep
    output_rep: !MoveRep
    emb_dim: 64
    num_decoder_layers: 2
    num_encoder_layers: 4

opt: !Adam()
    lr: !!float 1e-4
