# Convolutional ResNet model configuration for chess
# Uses Leela Chess Zero board representation (8x8x20)

pretrain_context: !PreTrainContext()
    train_fn: !train_step
    eval_fn: !eval_model

    train_dl: !DataLoader()
        dataset: !ChessData()
            path: /nfs/stonefish/data/train_lczero.csv
            input_rep: !LczeroRep  # Will need to create this
            output_rep: !MoveEnum
        batch_size: 256
        shuffle: True
        drop_last: True

    test_dl: !DataLoader()
        dataset: !ChessData()
            path: /nfs/stonefish/data/test_lczero.csv
            input_rep: !LczeroRep
            output_rep: !MoveEnum
        batch_size: 256
        shuffle: True

model: !ChessConvNet()
    input_channels: 20
    num_filters: 256
    num_blocks: 8
    output_dim: 5700

opt: !Adam()
    lr: !!float 1e-4
