
input_rep: !BoardRep
output_rep: !MoveRep

logging: !Logger
    output_dir: /nfs/fishtank/testing
    log_file: basic.txt
    overwrite: True

model: !BaseModel
    emb_dim: 32

opt: !Adam
    lr: !!float 1e-3

train_dl: !DataLoader
    dataset: !ChessData
        path: /nfs/one_train.csv 
    batch_size: 256
    shuffle: True
    drop_last: True

test_dl: !DataLoader
    dataset: !ChessData
        path: /nfs/one_test.csv 
    batch_size: 512
    shuffle: True
