
rl_context: !RLContext()
    steps: 2
    eval_fn: !ChessEvalContext()
    eval_freq: 200

env: !CChessEnvTorch()
    n: 8
    draw_reward: -1

model: !ACBase()
    input_rep: !CBoardRep
    output_rep: !MoveEnum

opt: !Adam()
