

pretrain_context: !PreTrainContext()
    train_fn: !seq_train_step
    eval_fn: !seq_eval_model

    train_dl: !DataLoader()
        dataset: !ChessData()
            path: /nfs/one_train.csv 
            input_rep: !BoardRep
            output_rep: !MoveRep
        batch_size: 256
        shuffle: True
        drop_last: True
    
    test_dl: !DataLoader()
        dataset: !ChessData()
            path: /nfs/one_test.csv 
            input_rep: !BoardRep
            output_rep: !MoveRep
        batch_size: 256
        shuffle: True
    
model: !BaseModel()
    input_rep: !BoardRep
    output_rep: !MoveRep

opt: !Adam()
    lr: !!float 1e-4

