
rl_context: !RLContext()
    steps: 128
    eval_fn: !ChessEvalContext()
    eval_freq: 100

env: !CChessEnvTorch()
    n: 128
    draw_reward: -1

model: !ACBase()
    input_rep: !CBoardRep
    output_rep: !MoveEnum

opt: !Adam()
