
input_rep: !BoardRep
output_rep: !MoveRep

logging: !Logger
    output_dir: /nfs/fishtank/openai
    log_file: basic.txt
    overwrite: True

model: !BaseModel
    emb_dim: 256

opt: !Adam
    lr: !!float 1e-4
    betas: !!python/tuple [0.9, 0.98]
    eps: !!float 1e-9

train_dl: !DataLoader
    dataset: !ChessData
        path: ./data/train_mondo_5.csv 
    batch_size: 512
    shuffle: True
    drop_last: True

test_dl: !DataLoader
    dataset: !ChessData
        path: ./data/test_mondo_5.csv 
    batch_size: 512
    shuffle: True
