# Convolutional ResNet configuration for chess move prediction
# Uses Leela Chess Zero board representation (8x8x20)

model:
  _target_: stonefish.resnet.ChessConvNet
  input_channels: 20
  num_filters: 256
  num_blocks: 8
  output_dim: 5700

dataset:
  _target_: stonefish.dataset.LczeroChessDataset
  split: train
  sample_size: 100000
  dataset_name: mkrum/ParsedChess

val_dataset:
  _target_: stonefish.dataset.LczeroChessDataset
  split: test
  sample_size: 10000
  dataset_name: mkrum/ParsedChess

dataloader:
  batch_size: 128  # Smaller batch size for conv models
  shuffle: true
  num_workers: 4
  pin_memory: true
  drop_last: true

val_dataloader:
  batch_size: 128
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005  # Lower learning rate for conv models
  weight_decay: 0.01

loss:
  _target_: torch.nn.CrossEntropyLoss

training:
  epochs: 10
  log_interval: 100
  save_interval: 1000
  output_dir: models/chess_convnet_lczero

# Optional wandb config
wandb:
  project: chess-resnet
  name: convnet-lczero-8x8x20
  tags: [convnet, lczero, chess, conv2d]
