
rl_context: !TwoModelRLContext()
    steps: 128
    eval_fn: !ChessEvalContext()
    entropy_weight: 0.0
    eval_freq: 500
    polyak_factor: .001

env: !CChessEnvTorchTwoPlayer()
    n: 28
    draw_reward: 0.0
    invert: true
    max_random: 10

model: !TBased()
    input_rep: !CBoardRep
    output_rep: !MoveRep

opt: !Adam()
    lr: !!float 1e-3
