
env: !CChessEnvTorch()
    n: 16
    draw_reward: -1

model: !ACBase()
    input_rep: !CBoardRep
    output_rep: !MoveEnum

#load_policy: /nfs/fishtank/anotherone/model_1.pth

opt: !Adam()
    lr: !!float 1e-4
