
rl_context: !SLRLAgainstSFContext()
    steps: 80
    eval_fn: !ChessEvalContext()
    eval_freq: 500
    entropy_weight: 0.0 
    value_weight: 0.0
    policy_weight: 0.0
    sl_weight: 0.0

env: !CChessEnvTorchTwoPlayer()
    n: 32
    invert: true
    draw_reward: 0
    max_random: 10

model: !TBased()
    input_rep: !CBoardRep
    output_rep: !MoveRep

opt: !Adam()
