
input_rep: !BoardRep
output_rep: !MoveRep

logging: !Logger
    output_dir: /nfs/fishtank/newone
    log_file: basic.txt
    overwrite: True

model: !BaseModel
    emb_dim: 256

opt: !Adam
    lr: !!float 1e-4

train_dl: !DataLoader
    dataset: !CEChessData
        path: /nfs/stonefish/data/train_mondo_5.csv 
    batch_size: 256
    shuffle: True
    drop_last: True

test_dl: !DataLoader
    dataset: !CEChessData
        path: /nfs/stonefish/data/test_mondo_5.csv 
    batch_size: 512
    shuffle: True
