
rl_context: !RLContext()
    steps: 32
    selfplay: True

env: !CChessEnvTorchTwoPlayer()
    n: 512
    draw_reward: -1

model: !ACBase()
    input_rep: !CBoardRep
    output_rep: !MoveEnum

opt: !Adam()
    lr: !!float 1e-4
