# Simple evaluation config for ConvNet model - matches latest_checkpoint.pth
model: !ChessConvNet()
    input_channels: 20
    num_filters: 128
    num_blocks: 8
    output_dim: 5700

agent: !ModelChessAgent()
    model_type: conv
    temperature: 1.0
    sample: true
