pretrain_context: !PreTrainContext()
    epochs: 5
    eval_freq: 1000
    gradient_clip: 1.0

    train_fn: !train_step
    eval_fn: !eval_model

    agent_eval_fn: !training_agent_eval()
        agent_config: !ModelChessAgent
            model_type: conv
            temperature: 1.0
            sample: true
        games_vs_random: 10
        games_vs_stockfish: 10
        stockfish_depth: 1

    train_dl: !DataLoader()
        dataset: !ChessDataset()
            split: train
            sample_size: 1000
        batch_size: 2
        shuffle: True
        drop_last: True
        collate_fn: null

    test_dl: !DataLoader()
        dataset: !ChessDataset()
            split: test
            sample_size: 50000
        batch_size: 2
        shuffle: True
        collate_fn: null

model: !ChessConvNet()
    input_channels: 20
    num_filters: 1
    num_blocks: 1
    output_dim: 5700

agent: !ModelChessAgent()
    model_type: conv
    temperature: 1.0
    sample: true

opt: !Adam()
    lr: !!float 5e-4
