pretrain_context: !PreTrainContext()
    epochs: 5
    eval_freq: 1000
    gradient_clip: 1.0

    train_fn: !train_step
    eval_fn: !eval_model

    agent_eval_fn: !training_agent_eval()
        agent_config: !ModelChessAgent
            temperature: 1.0
            sample: true
        games_vs_random: 50
        games_vs_stockfish: 50
        stockfish_depth: 1

    train_dl: !DataLoader()
        dataset: !ChessDataset()
            split: train
        batch_size: 512
        shuffle: True
        drop_last: True
        collate_fn: null

    test_dl: !DataLoader()
        dataset: !ChessDataset()
            split: test
            sample_size: 50000
        batch_size: 512
        shuffle: True
        collate_fn: null

model: !ChessResNet()
    input_dim: 69
    hidden_dim: 2048
    num_blocks: 2
    output_dim: 5700

agent: !ModelChessAgent()
    temperature: 1.0
    sample: true

opt: !Adam()
    lr: !!float 5e-4
