pretrain_context: !PreTrainContext()
    epochs: 5
    eval_freq: 1000
    gradient_clip: 1.0
    compile_model: true
    compile_mode: max-autotune

    train_fn: !train_step
    eval_fn: !eval_model

    agent_eval_fn: !training_agent_eval()
        agent_config: !ModelChessAgent
            temperature: 1.0
            sample: true
        games_vs_random: 100
        games_vs_stockfish: 100
        stockfish_depth: 1

    train_dl: !DataLoader()
        dataset: !ChessDataset()
            split: train
            streaming: true
            dataset_name: mkrum/LichessParsedBlitz
        batch_size: 512
        shuffle: False
        drop_last: False
        collate_fn: null
        num_workers: 1
        pin_memory: false
        prefetch_factor: 2

    test_dl: !DataLoader()
        dataset: !ChessDataset()
            split: test
            sample_size: 1000
        batch_size: 128
        shuffle: True
        collate_fn: null
        num_workers: 1
        pin_memory: false
        prefetch_factor: 2

model: !ChessConvNet()
    input_channels: 20
    num_filters: 128
    num_blocks: 2
    output_dim: 5632

agent: !ModelChessAgent()
    temperature: 1.0
    sample: true

opt: !Adam()
    lr: !!float 5e-4
