
pretrain_context: !PreTrainContext()
    train_fn: !seq_train_step
    eval_fn: !seq_eval_model

    train_dl: !DataLoader()
        dataset: !TTTData()
            path: ./data/ttt_easy_train.csv
            input_rep: !TTTBoardRep
            output_rep: !TTTMoveRep
        batch_size: 1024
        shuffle: True
        drop_last: True

    test_dl: !DataLoader()
        dataset: !TTTData()
            path: ./data/ttt_easy_test.csv
            input_rep: !TTTBoardRep
            output_rep: !TTTMoveRep
        batch_size: 1024
        shuffle: True

model: !BaseModel()
    emb_dim: 32
    num_encoder_layers: 2
    num_decoder_layers: 2
    input_rep: !TTTBoardRep
    output_rep: !TTTMoveRep

opt: !Adam()
    lr: !!float 1e-4
