
rl_context: !RLContext()
    steps: 3
    eval_fn: !EvalContext()
        eval_env: !TTTEnvTwoPlayer()
            n: 1

env: !TTTEnv()
    n: 64

input_rep: !BoardRep
output_rep: !MoveRep

model: !SimpleRL()

opt: !Adam()
    lr: !!float 1e-3
