
rl_context: !TwoModelRLContext()
    steps: 64
    eval_fn: !TTTEvalContext()
    entropy_weight: 0.0
    polyak_factor: .01

env: !TTTEnvTwoPlayer()
    n: 64

model: !SimpleRL()

opt: !Adam()
    lr: !!float 1e-3
